spring:
  application:
    name: movie-service
  datasource:
    url: ${USER_SERVICE_SPRING_DATASOURCE_URL}
    username: ${USER_SERVICE_SPRING_DATASOURCE_USERNAME}
    password: ${USER_SERVICE_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8082 