spring:
  application:
    name: common

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000