spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieapp
    username: ${USER_SERVICE_SPRING_DATASOURCE_USERNAME}
    password: ${USER_SERVICE_SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      INDENT_OUTPUT: true
