name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Corretto JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-forcefix
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check gradlew permissions
        run: ls -l gradlew

      - name: Make gradlew executable (fallback)
        run: chmod +x gradlew

      - name: Debug gradlew launch
        run: |
          echo "gradlew hash:"
          sha256sum gradlew
          echo "gradlew file info:"
          file gradlew
          echo "gradlew first line:"
          head -n 1 gradlew

      - name: Build and Test with Gradle
        run: ./gradlew clean build --no-daemon
