name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: movieapp
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: MyNewSecurePass123
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SPRING_PROFILES_ACTIVE: local

      # User Service DB
      USER_SERVICE_SPRING_DATASOURCE_USERNAME: postgres
      USER_SERVICE_SPRING_DATASOURCE_PASSWORD: MyNewSecurePass123
        # USER_SERVICE_SPRING_DATASOURCE_USERNAME: ${{ secrets.USER_SERVICE_SPRING_DATASOURCE_USERNAME }}
        # USER_SERVICE_SPRING_DATASOURCE_PASSWORD: ${{ secrets.USER_SERVICE_SPRING_DATASOURCE_PASSWORD }}

      # Movie Service DB
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      # Recommendation Service DB
#      RECOMMENDATION_SERVICE_SPRING_DATASOURCE_URL: ${{ secrets.RECOMMEND_DB_URL }}
#      RECOMMENDATION_SERVICE_SPRING_DATASOURCE_USERNAME: ${{ secrets.RECOMMEND_DB_USERNAME }}
#      RECOMMENDATION_SERVICE_SPRING_DATASOURCE_PASSWORD: ${{ secrets.RECOMMEND_DB_PASSWORD }}

      # Notification Service DB (optional example)
#      NOTIFICATION_SERVICE_SPRING_DATASOURCE_URL: ${{ secrets.NOTIFICATION_DB_URL }}
#      NOTIFICATION_SERVICE_SPRING_DATASOURCE_USERNAME: ${{ secrets.NOTIFICATION_DB_USERNAME }}
#      NOTIFICATION_SERVICE_SPRING_DATASOURCE_PASSWORD: ${{ secrets.NOTIFICATION_DB_PASSWORD }}

      # AWS configs (common)
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # Active profile (test)
#      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Corretto JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-forcefix
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check gradlew permissions
        run: ls -l gradlew

      - name: Make gradlew executable (fallback)
        run: chmod +x gradlew

      - name: Debug gradlew launch
        run: |
          echo "gradlew hash:"
          sha256sum gradlew
          echo "gradlew file info:"
          file gradlew
          echo "gradlew first line:"
          head -n 1 gradlew

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Postgres is up" && break
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Build and Test with Gradle
        run: ./gradlew clean build --no-daemon
